In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from pydataset import data

|               | pred dog   | pred cat   |
|:------------  |-----------:|-----------:|
| actual dog    |         46 |         7  |
| actual cat    |         13 |         34 |

cat = pos
dog = neg



2. In the context of this problem, what is a false positive?
    pred a cat and actually a dog
   In the context of this problem, what is a false negative?
   pred a dog and actually a cat 
   How would you describe this model?
   ?

In [4]:
df = pd.read_csv('c3.csv')
df.head()

      actual     model1  model2     model3
0  No Defect  No Defect  Defect  No Defect
1  No Defect  No Defect  Defect     Defect
2  No Defect  No Defect  Defect  No Defect
3  No Defect     Defect  Defect     Defect
4  No Defect  No Defect  Defect  No Defect

3.
An internal team wants to investigate the cause of the manufacturing defects. They tell you that they want to identify as many of the ducks that have a defect as possible. 

Which evaluation metric would be appropriate here? 
recall

Which model would be the best fit for this use case?
recall

Recently several stories in the local news have come out highlighting customers who received a rubber duck with a defect, and portraying C3 in a bad light. The PR team has decided to launch a program that gives customers with a defective duck a vacation to Hawaii. They need you to predict which ducks will have defects, but tell you the really don't want to accidentally give out a vacation package when the duck really doesn't have a defect. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

precison- minimize false positive

In [6]:
paws = pd.read_csv('gives_you_paws.csv')
paws.head(10)

  actual model1 model2 model3 model4
0    cat    cat    dog    cat    dog
1    dog    dog    cat    cat    dog
2    dog    cat    cat    cat    dog
3    dog    dog    dog    cat    dog
4    cat    cat    cat    dog    dog
5    dog    dog    dog    dog    dog
6    cat    cat    cat    cat    dog
7    cat    dog    cat    cat    dog
8    dog    dog    cat    dog    dog
9    dog    cat    dog    cat    dog

In [ ]:
model_accuracy = (paws.actual == paws.model1,paws.model2,paws.model3).mean()
baseline_accuracy = (paws.actual == df.baseline_prediction).mean()

print(f'   model accuracy: {model_accuracy:.2%}')
print(f'baseline accuracy: {baseline_accuracy:.2%}')

In [26]:
paws['model_accuracy']=paws[['model1','model2','model3']].mean(axis=1)
paws.head(10)

  actual model1 model2 model3 model4 baseline_prediction  model_accuracy
0    cat    cat    dog    cat    dog                True             NaN
1    dog    dog    cat    cat    dog                True             NaN
2    dog    cat    cat    cat    dog                True             NaN
3    dog    dog    dog    cat    dog                True             NaN
4    cat    cat    cat    dog    dog                True             NaN
5    dog    dog    dog    dog    dog                True             NaN
6    cat    cat    cat    cat    dog                True             NaN
7    cat    dog    cat    cat    dog                True             NaN
8    dog    dog    cat    dog    dog                True             NaN
9    dog    cat    dog    cat    dog                True             NaN